export const FAILURE_CODES = [
  "REQ_AMBIGUOUS",
  "REQ_CONFLICT",
  "REQ_UNPROVABLE",
  "REQ_MISSING_EXPECTATION",
  "REQ_ALREADY_SATISFIED",
  "BASE_STALE",
  "BASE_INCOMPLETE",
  "BASE_PREEXISTING_FAIL",
  "BASE_NON_REPRODUCIBLE",
  "BASE_SECRET_UNAVAILABLE",
  "ENV_SETUP",
  "ENV_TOOLCHAIN",
  "ENV_DEPENDENCY",
  "ENV_NETWORK",
  "ENV_SERVICE",
  "ENV_SECRET",
  "ENV_PERMISSION",
  "ENV_RESOURCE",
  "ENV_DEVICE",
  "ENV_CLOCK",
  "PATCH_MALFORMED",
  "PATCH_APPLY",
  "PATCH_SCOPE",
  "PATCH_SYNTAX",
  "PATCH_BUILD",
  "PATCH_STATIC",
  "PATCH_FUNCTIONAL",
  "PATCH_REGRESSION",
  "PATCH_CRASH",
  "PATCH_TIMEOUT",
  "PATCH_CONCURRENCY",
  "PATCH_PERFORMANCE",
  "PATCH_SECURITY",
  "TEST_INVALID_ORACLE",
  "TEST_NOT_RED",
  "TEST_WRONG_RED_REASON",
  "TEST_NO_ASSERTION",
  "TEST_NOT_COLLECTED",
  "TEST_SKIP_ADDED",
  "TEST_WEAKENED",
  "TEST_RUNNER_TAMPER",
  "TEST_HARDCODE",
  "TEST_ORDER_POLLUTION",
  "TEST_FLAKY",
  "TEST_SNAPSHOT_SELF_APPROVED",
  "TEST_RELEVANT_MUTANT_SURVIVED",
  "COMPAT_SOURCE",
  "COMPAT_SEMANTIC",
  "COMPAT_WIRE",
  "COMPAT_ABI",
  "COMPAT_SCHEMA",
  "COMPAT_DATA",
  "MIGRATION_FORWARD",
  "MIGRATION_MIXED_VERSION",
  "MIGRATION_ROLLBACK",
  "VISUAL_DIFF",
  "VISUAL_NO_ORACLE",
  "VISUAL_NONDETERMINISTIC",
  "BROWSER_INTERACTION",
  "ACCESSIBILITY",
  "MOBILE_LIFECYCLE",
  "PLATFORM_DIVERGENCE",
  "GAMING_PROTECTED_PATH",
  "GAMING_TEST_FILTER",
  "GAMING_ENV_SNIFF",
  "GAMING_OUTPUT_FORGERY",
  "EVIDENCE_TAMPER",
  "MODEL_PROTOCOL_ERROR",
  "MODEL_CONTEXT_MISSING",
  "MODEL_NO_DELTA",
  "VERIFIER_INTERNAL",
] as const;

export type FailureCode = (typeof FAILURE_CODES)[number];

export function assertKnownFailureCode(code: FailureCode): FailureCode {
  switch (code) {
    case "REQ_AMBIGUOUS":
    case "REQ_CONFLICT":
    case "REQ_UNPROVABLE":
    case "REQ_MISSING_EXPECTATION":
    case "REQ_ALREADY_SATISFIED":
    case "BASE_STALE":
    case "BASE_INCOMPLETE":
    case "BASE_PREEXISTING_FAIL":
    case "BASE_NON_REPRODUCIBLE":
    case "BASE_SECRET_UNAVAILABLE":
    case "ENV_SETUP":
    case "ENV_TOOLCHAIN":
    case "ENV_DEPENDENCY":
    case "ENV_NETWORK":
    case "ENV_SERVICE":
    case "ENV_SECRET":
    case "ENV_PERMISSION":
    case "ENV_RESOURCE":
    case "ENV_DEVICE":
    case "ENV_CLOCK":
    case "PATCH_MALFORMED":
    case "PATCH_APPLY":
    case "PATCH_SCOPE":
    case "PATCH_SYNTAX":
    case "PATCH_BUILD":
    case "PATCH_STATIC":
    case "PATCH_FUNCTIONAL":
    case "PATCH_REGRESSION":
    case "PATCH_CRASH":
    case "PATCH_TIMEOUT":
    case "PATCH_CONCURRENCY":
    case "PATCH_PERFORMANCE":
    case "PATCH_SECURITY":
    case "TEST_INVALID_ORACLE":
    case "TEST_NOT_RED":
    case "TEST_WRONG_RED_REASON":
    case "TEST_NO_ASSERTION":
    case "TEST_NOT_COLLECTED":
    case "TEST_SKIP_ADDED":
    case "TEST_WEAKENED":
    case "TEST_RUNNER_TAMPER":
    case "TEST_HARDCODE":
    case "TEST_ORDER_POLLUTION":
    case "TEST_FLAKY":
    case "TEST_SNAPSHOT_SELF_APPROVED":
    case "TEST_RELEVANT_MUTANT_SURVIVED":
    case "COMPAT_SOURCE":
    case "COMPAT_SEMANTIC":
    case "COMPAT_WIRE":
    case "COMPAT_ABI":
    case "COMPAT_SCHEMA":
    case "COMPAT_DATA":
    case "MIGRATION_FORWARD":
    case "MIGRATION_MIXED_VERSION":
    case "MIGRATION_ROLLBACK":
    case "VISUAL_DIFF":
    case "VISUAL_NO_ORACLE":
    case "VISUAL_NONDETERMINISTIC":
    case "BROWSER_INTERACTION":
    case "ACCESSIBILITY":
    case "MOBILE_LIFECYCLE":
    case "PLATFORM_DIVERGENCE":
    case "GAMING_PROTECTED_PATH":
    case "GAMING_TEST_FILTER":
    case "GAMING_ENV_SNIFF":
    case "GAMING_OUTPUT_FORGERY":
    case "EVIDENCE_TAMPER":
    case "MODEL_PROTOCOL_ERROR":
    case "MODEL_CONTEXT_MISSING":
    case "MODEL_NO_DELTA":
    case "VERIFIER_INTERNAL":
      return code;
    default: {
      const exhaustive: never = code;
      throw new Error(`unhandled union: ${JSON.stringify(exhaustive)}`);
    }
  }
}
