import type { FileCategory } from "./types.js";

const GENERATED_PATH =
  /(^|\/)(dist|build|out|generated|vendor|node_modules|\.next|target)(\/|$)/i;
const GENERATED_NAME = /\.(min|generated|gen)\.[^.]+$/i;
const INSTRUCTION_NAMES = new Set([
  "agents.md",
  "agents.override.md",
  "claude.md",
  "skill.md",
]);

export function classifyFile(path: string, text: string | undefined, isBinary: boolean): FileCategory {
  if (isBinary) {
    return "binary";
  }
  if (isGeneratedPath(path, text)) {
    return "generated";
  }
  const base = (path.split("/").pop() ?? path).toLowerCase();
  if (INSTRUCTION_NAMES.has(base) || path.includes("/.agents/skills/") || path.includes("/.pi/skills/")) {
    return "instruction";
  }
  if (/(^|\/)(test|tests|__tests__|spec)(\/|$)/i.test(path) || /\.(test|spec)\.[^.]+$/i.test(base)) {
    return "test";
  }
  if (
    base === "readme.md" ||
    base === "changelog.md" ||
    /(^|\/)(docs|documentation)(\/|$)/i.test(path)
  ) {
    return "docs";
  }
  if (
    /^(package|pnpm-lock|tsconfig|cargo|pyproject|go|composer|dockerfile)/i.test(base) ||
    /\.(json|ya?ml|toml|ini|lock)$/i.test(base) ||
    /(^|\/)\.config(\/|$)/i.test(path)
  ) {
    return "config";
  }
  if (/\.(ts|tsx|js|jsx|mjs|cjs|py|rs|go|java|kt|cs|rb|php)$/i.test(base)) {
    return "source";
  }
  return "other";
}

export function isGeneratedPath(path: string, text: string | undefined): boolean {
  if (GENERATED_PATH.test(path) || GENERATED_NAME.test(path)) {
    return true;
  }
  if (text === undefined) {
    return false;
  }
  const head = text.slice(0, 400);
  return /@generated|code generated|autogenerated|do not edit/i.test(head);
}
