import { type HttpOperationSpec } from "./http.js";

export const HTTP_OPERATIONS: readonly HttpOperationSpec[] = [
  {
    operationId: "createProject",
    method: "POST",
    path: "/v1/projects",
    audiences: ["admin"],
    requestSchemaName: "CreateProjectRequest",
    success: [{ status: 201, schemaName: "CreateProjectResponse" }],
    class: "mut-sync",
    errorProfile: "R+J+I",
    responseHeaders: ["Location", "ETag", "Operation-Id"],
  },
  {
    operationId: "getProject",
    method: "GET",
    path: "/v1/projects/{projectId}",
    audiences: ["admin", "broker"],
    requestSchemaName: null,
    success: [
      { status: 200, schemaName: "ProjectProjection" },
      { status: 304, schemaName: null },
    ],
    class: "read",
    errorProfile: "R",
    responseHeaders: ["ETag", "Cache-Control"],
  },
  {
    operationId: "updateProjectPolicy",
    method: "PUT",
    path: "/v1/projects/{projectId}/policy",
    audiences: ["admin", "broker"],
    requestSchemaName: "UpdateProjectPolicyRequest",
    success: [{ status: 200, schemaName: "ProjectProjection" }],
    class: "mut-sync",
    errorProfile: "R+J+I+P",
    responseHeaders: ["ETag", "Operation-Id"],
  },
  {
    operationId: "setProjectTrust",
    method: "POST",
    path: "/v1/projects/{projectId}:set-trust",
    audiences: ["admin", "broker"],
    requestSchemaName: "SetProjectTrustRequest",
    success: [{ status: 200, schemaName: "ProjectProjection" }],
    class: "mut-sync",
    errorProfile: "R+J+I+P",
    responseHeaders: ["ETag", "Operation-Id"],
  },
  {
    operationId: "createProjectApprovalChallenge",
    method: "POST",
    path: "/v1/projects/{projectId}/approval-challenges",
    audiences: ["broker"],
    requestSchemaName: "ApprovalChallengeRequest",
    success: [{ status: 201, schemaName: "ArtifactEnvelopeApprovalChallenge" }],
    class: "mut-sync",
    errorProfile: "R+J+I",
    responseHeaders: ["Location", "Operation-Id"],
  },
  {
    operationId: "commitProjectApproval",
    method: "PUT",
    path: "/v1/projects/{projectId}/approvals/{approvalId}",
    audiences: ["broker"],
    requestSchemaName: "CommitApprovalRequest",
    success: [
      { status: 201, schemaName: "CommitApprovalResponse" },
      { status: 200, schemaName: "CommitApprovalResponse" },
    ],
    class: "mut-sync",
    errorProfile: "R+J+I",
    responseHeaders: ["Location", "Operation-Id"],
  },
  {
    operationId: "createWorkspace",
    method: "POST",
    path: "/v1/projects/{projectId}/workspaces",
    audiences: ["broker"],
    requestSchemaName: "CreateWorkspaceRequest",
    success: [{ status: 201, schemaName: "WorkspaceProjection" }],
    class: "mut-sync",
    errorProfile: "R+J+I+P",
    responseHeaders: ["Location", "ETag", "Operation-Id"],
  },
  {
    operationId: "createRun",
    method: "PUT",
    path: "/v1/projects/{projectId}/runs/{runId}",
    audiences: ["broker"],
    requestSchemaName: "CreateRunRequest",
    success: [{ status: 201, schemaName: "RunProjection" }],
    class: "mut-sync",
    errorProfile: "R+J+I",
    responseHeaders: ["Location", "ETag", "Operation-Id"],
  },
  {
    operationId: "getRun",
    method: "GET",
    path: "/v1/projects/{projectId}/runs/{runId}",
    audiences: ["broker"],
    requestSchemaName: null,
    success: [
      { status: 200, schemaName: "RunProjection" },
      { status: 304, schemaName: null },
    ],
    class: "read",
    errorProfile: "R",
    responseHeaders: ["ETag", "Cache-Control"],
  },
  {
    operationId: "listRunEvents",
    method: "GET",
    path: "/v1/projects/{projectId}/runs/{runId}/events",
    audiences: ["broker"],
    requestSchemaName: "HttpEventsQuery",
    success: [{ status: 200, schemaName: "RunEventPage" }],
    class: "read",
    errorProfile: "R+400",
    responseHeaders: ["Cache-Control"],
  },
  {
    operationId: "listRunArtifacts",
    method: "GET",
    path: "/v1/projects/{projectId}/runs/{runId}/artifacts",
    audiences: ["broker"],
    requestSchemaName: "HttpArtifactsQuery",
    success: [{ status: 200, schemaName: "RunArtifactPage" }],
    class: "read",
    errorProfile: "R+400",
    responseHeaders: ["Cache-Control"],
  },
  {
    operationId: "provideRunInput",
    method: "POST",
    path: "/v1/projects/{projectId}/runs/{runId}:provide-input",
    audiences: ["broker"],
    requestSchemaName: "ProvideInputRequest",
    success: [{ status: 202, schemaName: "OperationProjection" }],
    class: "mut-run",
    errorProfile: "R+J+I+P+L",
    responseHeaders: ["Location", "ETag", "Operation-Id"],
  },
  {
    operationId: "requestRunRepair",
    method: "POST",
    path: "/v1/projects/{projectId}/runs/{runId}:request-repair",
    audiences: ["broker"],
    requestSchemaName: "RequestRepairRequest",
    success: [{ status: 202, schemaName: "OperationProjection" }],
    class: "mut-run",
    errorProfile: "R+J+I+P+L",
    responseHeaders: ["Location", "ETag", "Operation-Id"],
  },
  {
    operationId: "cancelRun",
    method: "POST",
    path: "/v1/projects/{projectId}/runs/{runId}:cancel",
    audiences: ["broker"],
    requestSchemaName: "CancelRunRequest",
    success: [{ status: 202, schemaName: "OperationProjection" }],
    class: "mut-run",
    errorProfile: "R+J+I+P",
    responseHeaders: ["Location", "ETag", "Operation-Id"],
  },
  {
    operationId: "createRunApprovalChallenge",
    method: "POST",
    path: "/v1/projects/{projectId}/runs/{runId}/approval-challenges",
    audiences: ["broker"],
    requestSchemaName: "ApprovalChallengeRequest",
    success: [{ status: 201, schemaName: "ArtifactEnvelopeApprovalChallenge" }],
    class: "mut-sync",
    errorProfile: "R+J+I+P",
    responseHeaders: ["Location", "Operation-Id"],
  },
  {
    operationId: "commitRunApproval",
    method: "PUT",
    path: "/v1/projects/{projectId}/runs/{runId}/approvals/{approvalId}",
    audiences: ["broker"],
    requestSchemaName: "CommitApprovalRequest",
    success: [
      { status: 201, schemaName: "CommitApprovalResponse" },
      { status: 200, schemaName: "CommitApprovalResponse" },
    ],
    class: "mut-sync",
    errorProfile: "R+J+I+P",
    responseHeaders: ["Location", "Operation-Id"],
  },
  {
    operationId: "missingBlobs",
    method: "POST",
    path: "/v1/projects/{projectId}/blobs:missing",
    audiences: ["broker", "runner", "worker"],
    requestSchemaName: "MissingBlobsRequest",
    success: [{ status: 200, schemaName: "MissingBlobsResponse" }],
    class: "read",
    errorProfile: "R+J",
    responseHeaders: ["Cache-Control"],
  },
  {
    operationId: "putBlob",
    method: "PUT",
    path: "/v1/projects/{projectId}/blobs/sha256/{objectDigest}",
    audiences: ["broker", "runner", "worker"],
    requestSchemaName: null,
    success: [
      { status: 201, schemaName: null },
      { status: 204, schemaName: null },
    ],
    class: "content",
    errorProfile: "R+409+413+415+422",
    responseHeaders: ["Location", "ETag", "Repr-Digest"],
  },
  {
    operationId: "getBlob",
    method: "GET",
    path: "/v1/projects/{projectId}/blobs/sha256/{objectDigest}",
    audiences: ["broker", "runner", "worker"],
    requestSchemaName: null,
    success: [
      { status: 200, schemaName: null },
      { status: 206, schemaName: null },
      { status: 304, schemaName: null },
    ],
    class: "read",
    errorProfile: "R+416",
    responseHeaders: ["ETag", "Accept-Ranges", "Content-Digest", "Repr-Digest", "Cache-Control"],
  },
  {
    operationId: "commitSnapshot",
    method: "PUT",
    path: "/v1/projects/{projectId}/snapshots/{snapshotId}",
    audiences: ["broker"],
    requestSchemaName: "SnapshotCommitRequest",
    success: [
      { status: 201, schemaName: "SnapshotProjection" },
      { status: 200, schemaName: "SnapshotProjection" },
    ],
    class: "mut-sync",
    errorProfile: "R+J+I+L",
    responseHeaders: ["Location", "ETag", "Operation-Id"],
  },
  {
    operationId: "createRunnerEnrollmentChallenge",
    method: "POST",
    path: "/v1/admin/runner-enrollment-challenges",
    audiences: ["admin"],
    requestSchemaName: "CreateRunnerEnrollmentChallengeRequest",
    success: [{ status: 201, schemaName: "RunnerEnrollmentChallenge" }],
    class: "mut-sync",
    errorProfile: "R+J+I",
    responseHeaders: ["Location", "Operation-Id", "Cache-Control"],
  },
  {
    operationId: "revokeRunner",
    method: "POST",
    path: "/v1/admin/runners/{runnerId}:revoke",
    audiences: ["admin"],
    requestSchemaName: "RevokeRunnerRequest",
    success: [{ status: 204, schemaName: null }],
    class: "mut-sync",
    errorProfile: "R+J+I",
    responseHeaders: ["Operation-Id"],
  },
  {
    operationId: "enrollRunner",
    method: "PUT",
    path: "/v1/runners/{runnerId}:enroll",
    audiences: ["bootstrap"],
    requestSchemaName: "EnrollRunnerRequest",
    success: [{ status: 201, schemaName: "RunnerIdentityResponse" }],
    class: "mut-sync",
    errorProfile: "400,404,409,413,415,422,500,503",
    responseHeaders: ["Location", "Operation-Id", "Cache-Control"],
  },
  {
    operationId: "rotateRunnerCertificate",
    method: "POST",
    path: "/v1/runners/{runnerId}:rotate-certificate",
    audiences: ["runner"],
    requestSchemaName: "RotateRunnerCertificateRequest",
    success: [{ status: 201, schemaName: "RunnerIdentityResponse" }],
    class: "mut-sync",
    errorProfile: "R+J+I",
    responseHeaders: ["Location", "Operation-Id", "Cache-Control"],
  },
  {
    operationId: "leaseRunnerJob",
    method: "POST",
    path: "/v1/runner/jobs:lease",
    audiences: ["runner", "worker"],
    requestSchemaName: "RunnerLeaseRequest",
    success: [{ status: 200, schemaName: "RunnerLeaseResponse" }],
    class: "lease",
    errorProfile: "R+J+409+423",
    responseHeaders: ["Cache-Control"],
  },
  {
    operationId: "heartbeatOperation",
    method: "POST",
    path: "/v1/projects/{projectId}/operations/{operationId}:heartbeat",
    audiences: ["owning-runner", "worker"],
    requestSchemaName: "OperationHeartbeatRequest",
    success: [{ status: 200, schemaName: "OperationHeartbeatResponse" }],
    class: "lease",
    errorProfile: "R+J+409+410+423",
    responseHeaders: ["Cache-Control"],
  },
  {
    operationId: "completeOperation",
    method: "PUT",
    path: "/v1/projects/{projectId}/operations/{operationId}/result",
    audiences: ["owning-runner", "worker"],
    requestSchemaName: "OperationResultRequest",
    success: [{ status: 200, schemaName: "OperationProjection" }],
    class: "lease",
    errorProfile: "R+J+409+410+422+423",
    responseHeaders: ["ETag", "Cache-Control"],
  },
  {
    operationId: "getOperation",
    method: "GET",
    path: "/v1/projects/{projectId}/operations/{operationId}",
    audiences: ["broker", "owning-runner", "worker"],
    requestSchemaName: null,
    success: [
      { status: 200, schemaName: "OperationProjection" },
      { status: 304, schemaName: null },
    ],
    class: "read",
    errorProfile: "R",
    responseHeaders: ["ETag", "Cache-Control"],
  },
];
