export const packageName = "@pi-hec/state-store";

export {
  ARGON2ID_PRODUCTION_PARAMETERS,
  ARGON2ID_TEST_PARAMETERS,
  DB_RESPONSE_KEY_ID_PREFIX,
} from "./crypto.js";
export type { Argon2idParameters } from "./crypto.js";
export {
  CrashBeforeCommitError,
  SimulatedProcessTermination,
} from "./crash.js";
export type { CrashMode } from "./crash.js";
export {
  CardinalityError,
  ConflictError,
  IdempotencyConflictError,
  LeaseError,
  ReadOnlyRecoveryError,
  ReconcileRequiredError,
  StateVersionConflictError,
  StoreClosedError,
  StoreError,
  StoreLookupError,
  UntrustedProjectError,
} from "./errors.js";
export {
  checksumSqlBytes,
  defaultControlMigrationsDir,
  INITIAL_MIGRATION_NAME,
  INITIAL_MIGRATION_VERSION,
  loadMigrationSql,
  migrationFilePath,
} from "./migrations.js";
export {
  openStateStore,
  READ_ONLY_RECOVERY_MARKER,
  readOnlyRecoveryMarkerPath,
  StateStore,
} from "./database.js";
export type { OpenStateStoreOptions, SqlitePragmas } from "./database.js";
export type {
  ArtifactInput,
  ArtifactRecord,
  CompleteIdempotencyInput,
  CompleteOperationInput,
  CloudCallRecord,
  CloudTransportAttemptOutcome,
  CloudTransportAttemptRecord,
  CompleteCloudCallInput,
  RecordCloudTransportAttemptInput,
  SettleCloudCallTransportInput,
  TransitionCloudCallToDispatchingInput,
  CreateCloudCallInput,
  CreateProjectInput,
  CreateRunInput,
  CreateRunnerInput,
  CreateSnapshotInput,
  CreateWorkspaceInput,
  EnqueueOperationInput,
  EnrollmentInput,
  FailOperationInput,
  GrantRunnerInput,
  RevokeRunnerGrantInput,
  HeartbeatInput,
  HostAuthorityArtifactInput,
  HostAuthorityArtifactRecord,
  IdempotencyReplay,
  IdempotencyReservation,
  LeaseOperationInput,
  LeaseResult,
  OperationRecord,
  PersistRunEventInput,
  ProjectRecord,
  ReserveIdempotencyInput,
  SetProjectTrustInput,
  StoredRunEvent,
  UsageInput,
  UsageRecord,
  UsageEntryRecord,
  CloudCallOutcomeRecord,
  WorkspaceRecord,
  RunnerCertificateRecord,
  RunnerRecord,
  OperationScanRow,
  SnapshotRecord,
  RunArtifactRecord,
  EnrollmentChallengeRecord,
  InsertRunnerCertificateInput,
  OpenApprovalChallengeInput,
  ConsumeApprovalInput,
  ConsumeEnrollmentInput,
  UpdateProjectPolicyInput,
  RevokeRunnerInput,
  MarkOperationUnknownInput,
} from "./types.js";
